### ISSUE TITLE
Add method parsing

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#116]
E.g. methodName()

**Comment by phase** [comment]
I don't think you need an issue for every part of your parser, maybe just one.

**Comment by Michael2109** [comment]
Sorry I didn't think about this but do they come through as emails to people following? Also the reason why is I currently have nowhere else to log it and each issue would require a minimum of three classes. It was to ensure I would get everything sorted without missing any sections unless you could suggest the best method of doing so?

**Comment by phase** [comment]
A checklist in one issue would work. I check my GitHub notifications constantly, and it was surprising to have that many. I don't know if people get emails about them.

**Comment by Michael2109** [comment]
Ah I didn't realise we could do checklists! I'm rather new to using github
and didn't realise. Thank you for your message I'll get that changed.
