### ISSUE TITLE
Syntax for CudaText/Synwrite

### ISSUE THREAD

**Issue by Alexey-T** [Michael2109/Cobalt#14]
Seems easy to make "lexer" for Cudatext. it's like Java lexer. with changes. maybe you can do (if users need it) :)

**Comment by Michael2109** [comment]
Something like that sounds like a good idea. I think I will focus on an intellij plugin soon as I use intellij for the main project and it would be great for it to highlight everything. Neber used cudatext but could do that in the future.

**Comment by Alexey-T** [comment]
Okay,thanks
