### ISSUE TITLE
Calling of methods from within a class

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#223]
A method should be able to be called from within a class. 
```
let example(): void
    println("Do Something")

let otherExample(): void
    // Call method from within the class.
    example()
```

**Comment by DaricusDuncan** [comment]
@Michael2109  I would like to work on this open source project and really get involved if possible. I understand that I will have some great learning to do, but if there is room for a helping hand, I am capable of learning as I go.

**Comment by Michael2109** [comment]
Hi @DaricusDuncan ,
As of now I've stopped development on this. It's a massive project and I haven't looked at it in the last 6 months. You're welcome to check it out. If others were to join with this it possibly could be something. 
Michael

**Comment by DaricusDuncan** [comment]
@Michael2109  Thank you so much for the quick response and updating me on the status. I most certainly will check out the project anyway and poke around. I really am interested in just becoming better at Java and gaining some real world experience. I simply would like to be part of an open source team that is working on something that may make someone's day a little easier or even something big. It could even be not that exciting as long as I can volunteer some time here and there. I do not have a ton of experience programming in the Real World (Recent College Grad) and would like more exposure.

**Comment by Michael2109** [comment]
Ah I see. I only graduated around a year ago now so not too far off from me!     
This is all written in Scala which is similar to Java. If you haven't used it before I recommend looking it up. Teaches a lot of good practises and I prefer it a lot to Java now. 
I believe there are wiki pages explaining generally how the compiler all works. It was a very interesting project and I feel it helped me improve a lot. 
If you have any questions feel free to ask!

**Comment by DaricusDuncan** [comment]
Thank you so much and congratulations!! We are both graduates! 
I will look into Scala.
I appreciate all of the help and will reach out if I need to ask something.
If you ever need a hand with anything, just let me know as well.

**Comment by DaricusDuncan** [comment]
Is this project closed for good?

**Comment by Michael2109** [comment]
Making some changes at the moment! Decided to make a switch to using Haskell instead of Scala for the compiler. Been working on this recently and had it on Gitlab so now moving it here,

**Comment by DaricusDuncan** [comment]
Awesome! Will keep looking into it. Thanks.

**Comment by Michael2109** [comment]
Do you have any experience with using Haskell? Or any interest towards it?

**Comment by DaricusDuncan** [comment]
I do not have experience in it, but I can learn it. I have a book on it.

**Comment by Michael2109** [comment]
Ah that's good you've started that early! I wish I'd started looking into it sooner. I'll see how this goes over the next couple months and maybe if you're interested I'll give you a message.

**Comment by DaricusDuncan** [comment]
I greatly appreciate that and will continue studying. I have been trying to learn on my own since we last spoke. I am only 2 yrs out of school so I have much to learn.  Reach out to me definitely.

**Comment by Michael2109** [comment]
Ah I see. Well if you're interested in lower level stuff like compilers etc maybe check [this](https://markkarpov.com/megaparsec/parsing-simple-imperative-language.html) out? I've been really enjoying it and learned a lot. Haskell is the perfect language for parsing.

**Comment by DaricusDuncan** [comment]
Thank you so much. I will read over this. If I like it, I will let you know.

**Comment by Michael2109** [comment]
Great let me know if you need any help.

**Comment by Michael2109** [comment]
Hi @DaricusDuncan ,

How are you? 

Recently I've been working a lot on the project. I'm now at the stage that a basic 2d game can be written in Cobalt and compiled correctly!

I was wondering if you are interested in working on this project? 

Of course if it's not your kind of thing just let me know :) 

Michael

**Comment by DaricusDuncan** [comment]
Hi @Michael2109 ,

I am great. Hope all is well with you. That is super exciting that you can compile a game completely in Cobalt! I do not know if I am very knowledgeable yet with Haskell and Scale to be able to adequately help you. I considered purchasing [this](https://www.humblebundle.com/books/functional-programming-books?hmb_source=humble_home&hmb_medium=product_tile&hmb_campaign=mosaic_section_1_layout_index_2_layout_type_three_to_one_tile_index_3).

Daricus

**Comment by Michael2109** [comment]
It's strange you just sent me that link. I bought the whole bundle yesterday! I'd recommend it. I believe the books normally are over £10 each. 

I feel it could be just a matter of cloning the repo and taking a good look at how it works. My way of thinking is once you've spent around 2 weeks having a look at something new like this it all starts to click. Completely up to you of course. 

If you need anything let me know. I'm more then happy to find you some simple starter issues to work on if you would like. 

Hope this is all okay!

**Comment by DaricusDuncan** [comment]
Wow. Small world. I will go ahead and pick them up.

I think that I will just clone the repo and play around for a bit with it and see where it takes me. I appreciate you reaching out to me, but I think I will do what you asked first and try to become familiar with everything and later see if I can knock out a simple issue from you later.

You are a great help and I appreciate the immediate advice and suggestions. All of this really helps me feel more determined to contribute and help you out more in the near future.

**Comment by Michael2109** [comment]
Great!

One thing before you start you'll want to follow some tutorials for working with a tool called "Stack". It sets up a Haskell project etc. 

My email is michael.jhaywoods@gmail.com. If you want any info/explanation for anything just email me instead. I imagine there will be some hurdles at the start but after that it should all make sense.

**Comment by DaricusDuncan** [comment]
Thank you so much!!

I will look up some tutorials on "Stack" and try to set it up. 

Hopefully today I will have an hour or two to go through an example today and so I will likely email you even if it is nothing more than a simple update on where I currently am. I appreciate all the help seriously.

**Comment by Michael2109** [comment]
Hi Daricus,

I thought I would give you a message to see if you're still interesting in
contributing?

Recently I've been putting a lot of work into the project and I now have
one other working with me. If you be great if you're still up for it.

Michael

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DaricusDuncan** [comment]
@Michael2109 

Hi Michael,

I am definitely interested in contributing and helping out. I recently have had a job change and so I have been adjusting to the new workflow. I do not know how long it will take for me to be able to get more involved with this project. I am really glad that you started this up again and want to help where I can.

I am still here and everything. Just has been pretty busy this last month. Is there something small that I may be able to help with?

- Daricus

**Comment by Michael2109** [comment]
Ah that makes sense.

I think it might be best if you let me know when you have the project
compiling and executing properly first? After that I'm happy to find you
something to do. :)

There's no pressure with this too. If it's too much with your current work
then it may be best to leave it until you have more time on your hands etc.

Michael
