### ISSUE TITLE
Add ++ operator for combining arrays

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#245]

**Comment by Michael2109** [comment]
This almost works correctly. 
This will parse properly.
```
"x ++ \"String Literal\""
```
```
"\"String Literal 1\" ++ x"
```
I'm trying to understand why but for some reason having a string literal first causes it to only parse the string literal. To see this a test is commented out in `ArrayOpParserTest`.

**Comment by Michael2109** [comment]
What is left to complete on this and #475 ?

**Comment by FilipJanitor** [comment]
Here tests using literal lists. The other issue is finished and will be closed when merging.

**Comment by Michael2109** [comment]
Are you currently working on this or should I continue with the `cobalt-245` branch and add tests?

**Comment by FilipJanitor** [comment]
If you could add them that would be great as I am still not entirely sure about the array/list literals. Thanks

**Comment by Michael2109** [comment]
For now we can complete this and ignore array/list definitions. We already parse them correctly but we store  them as method calls. Instead we should  rename it as something more generic. 
Will do thank you.
