### ISSUE TITLE
Parser Tests

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#313]
All these tests should test the associated parser and also test `expressionParser'`. An example is in `BExprParserTest`.

**Base Parser**

- [x] Line comments
- [x] Symbol
- [x] Reserved word
- [x] Integer
- [x] Long
- [x] Float
- [x] Double
- [x] Parenthesis
- [x] Identifier

**Arithmetic / Boolean expression Parser**
- [x] Arithmetic expressions
- [x] Boolean expressions
- [x] Relational expressions

**Expression parser**
- [x] Model
- [x] Import
- [x] Constructor 
- [x] Method
- [x] Identifier 
- [x] String literal 
- [x] Assign (Missing tests for mutable)
- [x] Reassign 
- [x] Array append
- [x] Object method call
- [x] New class instance
- [x] Class variable
- [x] Annotation
- [x] If Else
- [x] Ternary
- [x] Method call
- [x] Lambda
- [x] Tuples

**Comment by Michael2109** [comment]
One set of tests I've not implemented yet is for modifier blocks. What are your opinions on them? Are they worth having or is the code neater without? 
It could be good that it groups code together depending on the modifier but in some cases they might not be of much use. It depends whether we thing it is worth it as it isn't difficult to implement.

**Comment by FilipJanitor** [comment]
Also for reference, this issue does not cover testing failing on syntactically incorrect input. This will need to be implemented separately.
