### ISSUE TITLE
The compiler should compile one file at a time instead of a directory

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#333]
The compiler should compile one file at a time. This would mean loading only public variables and methods into the symbol table for other classes and then only storing the selected class.

**Comment by Michael2109** [comment]
@FilipJanitor To double check do you consider this complete?

**Comment by FilipJanitor** [comment]
I don't know about the second part. What I did was just changing the argument of `compile` from a directory to list of files (their filepaths actually) with as little additional changes as possible - that means only removing the directory traversal and adjusting the filepath generation for `ASTData`).

It is possible that when generating some output in the future this might not be sufficient. I did not touch the symbol table or code generation. The data types `GeneratedCode` and `ASTData` contain some info about inputfiles so it might be necessary to make some additional changes.

**Comment by Michael2109** [comment]
Okay I'm thinking about this and there's more to this then I originally thought. 

We need it to loop through all files in the class path and generate the symbol table from them. This will be needed so we can check references etc are correct between each class.

**Comment by FilipJanitor** [comment]
Yeah, I did not touch the classpath either.  Do I understand correctly, that it will be used when for example recompiling a single file that includes/references other classes that are already compiled?

**Comment by Michael2109** [comment]
From what I understand we will run this on all files in the class path directory:

```
  let astDatas = zipWith (\filePath fileData -> generateAST filePath fileData) filteredFilePaths fileDatas

  -- Combines all class symbol tables for all ASTs
  let symbolTable = SymbolTable $ concat $ map (\ sTable -> classSymbolTables sTable) $ map (extractASTSymbolTable) astDatas
```

This then generates a symbol table containing all classes and their methods/public variables.  
From this we can then run `compileAST` on the individual files specified to be compiled. `compileAST` gets the symbol table passed to it so it allows for error checking and code generation to see what methods etc are accessible.
