### ISSUE TITLE
Generate Java byte code

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#343]
Instead of generating Java code we need to generate byte code. To do this we need to generate ASM code and compile and execute this to generate the byte code. This is going to be a bit more difficult as Haskell isn't on the JVM.

I've found [this](https://www.tweag.io/posts/2017-09-15-inline-java-tutorial.html). This could allow for us to directly compile the generated ASM code and execute it. (Avoids saving of files etc which would be a mess) 

This is what I'm thinking we need to do. Let me know if you feel there are alternative solutions. 

### Requirements 
- [ ] Function that takes a Java ASM class as a string and executes it
- [ ] When executed the Java ASM code should generate a byte code file (class file) in the output directory
- [ ] AST needs to generate ASM code. We can start with a  small subset of nodes first. 
- [ ] Full end-to-end testing taking test .cobalt files, compiling, executing and checking the output is correct

**Comment by Michael2109** [comment]
@FilipJanitor I've been trying to add `hs-java` as a dependency.
I've now set up a VM so I can use linux as `hs-java` requires `pkg-config` and `libzip-dev` which is horrible to get working in Windows. 
First I added `hs-java` to the cabal file.   
Using `stack solver --update-config` it will add everything needed. You then need to install `pkg-config` with `sudo apt-get pkgconfig` and `libzip` with `sudo apt-get libzip-dev`.    
I've managed to do all this but when doing `stack build` but it's having trouble compiling the `hs-java` library saying that types are incorrect.    
It would be great if you could give this a try when you are next available? There's no rush at the moment.

**Comment by FilipJanitor** [comment]
I will write it here for possible future reference despite the appropiate packages were already added to stack.yaml file.

The problem is, that the `hs-java` package depends on package `Glob` for patternmatching filepaths. In version 0.9.0 there was a change of type signature for function `System.FilePath.Glob.globDir` which broke `hs-java` build. Versions prior to 0.9.0 seem to be working okay.

**Comment by Michael2109** [comment]
I think it may be best for us to fork `hs-java` and fix the bug. Really we would rather avoid using older libraries as we may require the latest versions in the future.

**Comment by FilipJanitor** [comment]
I am already filling an issue in his repo.

**Comment by Michael2109** [comment]
hs-java now successfully generates byte code. We now need to write a function to run generated byte code. This will allow us to do full end to end testing.

**Comment by Michael2109** [comment]
I feel this is considered complete now. Overall we can generate bytecode and execute integration tests on the generated code. The implementing of how each node generates code will be separate issues.
