### ISSUE TITLE
Single line string literal is parsed incorrectly

### ISSUE THREAD

**Issue by FilipJanitor** [Michael2109/cobalt#348]
String with single double quotes is meant to be single line. As seen in `testStringLiteralUnfinishedDoubleLineFail` the string:

```
"first line     
 second line"
```

Is successfuly parsed and produces.
`"first line \n second line"`

This might cause problems beause as seen in test `testStringLiteralUnfinishedDoubleLineLeadingWhitespaceFail` the leading whitespace which depends on the context of surrounding code is also parsed and preserved into string literal.

**Comment by FilipJanitor** [comment]
This might be harder then it seems. I am still not sure about everything but there is a possibility to use different space consumer or try to implement what is left as an excercise here [https://github.com/mrkkrp/megaparsec-site/blob/master/tutorials/switch-from-parsec-to-megaparsec.md#what-happened-to-text.parsec.token](https://github.com/mrkkrp/megaparsec-site/blob/master/tutorials/switch-from-parsec-to-megaparsec.md#what-happened-to-text.parsec.token) or to tinker with what is provided here [https://github.com/mrkkrp/megaparsec/issues/26#issuecomment-138531695](https://github.com/mrkkrp/megaparsec/issues/26#issuecomment-138531695)

**Comment by Michael2109** [comment]
The way it's written in the tutorial makes it seem as though it wouldn't be too much work, Doesn't seem a nice one to implement necessarily though.

**Comment by FilipJanitor** [comment]
The tricky part seems to be in the fact, that `charLiteral` uses `readLitChar` under the hood, which is quite useful as it can correctly read almost everything, it just reads a newline too.

**Comment by Michael2109** [comment]
Could this be a matter of creating our own `charLiteral` function and writing a new `readLitChar` function that ignores newlines?

**Comment by FilipJanitor** [comment]
That is a possibility but I would like to avoid it, as it would be
reinventing a wheel pretty much. The functions are actually pretty powerful
- they corrextly parse escaping, octal chars, hex chars and I dont know
what else too. I contacted the Megaparsec dev with my question so hopefully
he will have some more elegant solution for us.

**Comment by Michael2109** [comment]
That makes sense. We can wait and see.
