### ISSUE TITLE
Command line options need to be added 

### ISSUE THREAD

**Issue by FilipJanitor** [Michael2109/cobalt#365]
- [x] classpath
- [x] destination directory
- [x] version
- [X] help
- [x] verbose 
- [x] debug mode

future possibilities

- [x] generate debug symbols to compiled files

extra
- [x] Testing of each command line option

**Comment by Michael2109** [comment]
I've noticed -p is used instead of -cp. Would it be okay to change that too? Also I've been changing a few things to get single files to compile correctly. I noticed that strings are used for the command line args so I've changed it to FilePath.

**Comment by FilipJanitor** [comment]
Well, for parsing arguments we are currently using `System.Console.GetOpt` which is essentially a Haskell port of the GNU getopt library. Thus it implements  [GNU convention](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) which prohibits multi char options preceeded with only one dash - it treats `-abc` as `-a -b -c`. 

Thanks for fixing the FilePath - it was just temporary measure to get things going. I didn't notice that the change was inconsistent with the rest.

**Comment by Michael2109** [comment]
Ah I see. I'm guessing this means it isn't just a small change?

**Comment by FilipJanitor** [comment]
I am afraid it is not - it would need some nontrivial workarounds. I am aware of the potential single character conflicts but I hope that since gcc can handle it the GNU convention should be sufficient.

**Comment by Michael2109** [comment]
How do we deal with options such as -classpath? As we will be wanting to do that.

**Comment by FilipJanitor** [comment]
Right now it is possible to use `-p CLASSPATH`, `-pCLASSPATH`, `--class-path CLASSPATH` and `--class-path=CLASSPATH`. The abbreviation p might not be what we want but it is simple to change it to any other single character.

I will try to add tests for the commandline arguments soon - it will clarify everything hopefully.

**Comment by Michael2109** [comment]
Okay I'll see what Scala does and compare between others. I feel it could be best to stick to how other compilers do it. In particular the Java one as this language will be on the JVM and most users would know how to use javac.

**Comment by FilipJanitor** [comment]
It seems like scalac and javac are not consistent either.

**Comment by Michael2109** [comment]
`source path for compiling all .cobalt files in a directory` isn't needed anymore is it? I think I added this at the start so if you feel everything else is done you can ignore that.

**Comment by FilipJanitor** [comment]
I don't know - you are right that was the original behaviour which we changed to compiling individual files. I tought of this option as some sort of a shortcut - not needing to enumerate all the files if they are conviniently stored in a directory. I dont know how will we support wildcards or what will be the use cases yet.

**Comment by Michael2109** [comment]
Ah I see. If you are happy to we can exclude this for now and we could possibly introduce it in the future if needed?

**Comment by FilipJanitor** [comment]
Ok - that is why I left it open like this - it was only a future suggestion. If you want to close the issue for now we can do it.
