### ISSUE TITLE
Add parameterized types

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#379]
Due to tests @mlutze has recently added it's made me realise a problem.  
Currently when defining a list we use `[String]`. This is similar to Haskell.
The problem with this is we may want to define other things. E.g. Lists or Arrays or other use other generic classes. Haskells syntax doesn't require anything like this.    
In order to solve this we need parsing of parameterized types to be added.    

`val example: ExampleClass[String] = new ExampleClass[String]()`

This means instead of parsers for array types in particular, we should probably have parsers for parameterized types instead.

**Comment by FilipJanitor** [comment]
Or we might use a different symbol altogether to separate it from arrays and lists.

**Comment by Michael2109** [comment]
I think there might be a few we would have to do this for which makes it a bit more difficult. 

I'm referring to Scala with this which has List, Array, ListBuffer, ArrayBuffer. This would be similar to what we want. Also this includes things like Sets, Maps and Queues. 

What do you have in mind?

**Comment by FilipJanitor** [comment]
Well I am not sure if I understand correctly what is the issue, but if it is in the brackets being used both for list/array operations/declarations and also for parametrizing generic classes, we can use `<` and `>` for the letter.

**Comment by mlutze** [comment]
I like the idea of following Scala, treating arrays as parameterized objects:

```
val arr: Array[String] = new Array[String](10)
```

**Comment by FilipJanitor** [comment]
So we would actually index to array (or any indexable collection like type) not using brackets but normal braces and brackets would be used for parametrising objects- do I understand correctly? Sorry I am not a Scalist.

**Comment by mlutze** [comment]
Sorry, that was not the best example; that was showing a declaration rather than an index. But yes, that is how Scala does it: `val item = arr(3)`.  Alternately, we could treat it as a typical Java-like collection object with `get(int)` and `set(int)`.

**Comment by Michael2109** [comment]
Yeah that should be it. 

Everything in our language should be objects including arrays (although I know arrays are technically objects in Java but don't extend Object). 

We will have to decide how to deal with accessing the lists/arrays. Scala doesnt use .get(i) like Java and instead directly accesses it.

**Comment by FilipJanitor** [comment]
Ok, I get it now - turns out the issue was about something different then I thought after all.

**Comment by Michael2109** [comment]
Parsing and tests added.
