### ISSUE TITLE
Defining a val/var alternative format

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#384]
Currently the format for  defining values and variables is like this.  

`val x: Int = 10`
`var x: Int = 10`

A big aim for this language is to have it highly readable and also to try and push towards immutability as default behaviour. 

With this in mind when I originally wrote the specification I thought this could be an alternative.

`x: Int = 10`
`mutable x: Int = 10`

This means that it would be very obvious when an object is mutable. Also it removes clutter when defining a val/var. 

Although there are these advantages it does mean when parsing we would only know it is a variable by the time it reads the `=` character in comparison to when it reads `val/var`.

**Comment by FilipJanitor** [comment]
Having at least some keyword when defining `val` (if we leave out the type to be infered) might help as a visual cue indicating that in fact a new `val` is being created  instead of the statement overwriting a previously defined mutable variable.

**Comment by Michael2109** [comment]
That is a very good point. Could be pretty confusing.

**Comment by Michael2109** [comment]
There's also F#'s way of writing it too. 

`let x = 10`
`let mutable x = 10`

I'm trying to throw around some other ideas for how this might be done.

**Comment by FilipJanitor** [comment]
Is the `val`/`var` what is going to be used?

**Comment by Michael2109** [comment]
Sorry I thought I'd added to this. I think val/var is best. I looked into using let and type inference etc but there seems to be limitations in what we can do.
