### ISSUE TITLE
Port from libzip to zip

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#394]
Currently the hs-java library uses `libzip` but this has some comparability issues with Windows. 
Instead we should use `zip`. 
Currently all code is commented out that uses `libzip`. This should all be added back in but moved over to `zip`.
Also if we do this we can submit the changes to portnov's hs-java and when he updates there's no reason to not shift to their version.

**Comment by Michael2109** [comment]
When this is complete it should also be added as a pull request for `hs-java`. if it is updated there we can then add `hs-java` as a dependency and avoid the licensing issues.

**Comment by FilipJanitor** [comment]
Even if it is not approved - after all, it works well with libzip now - we could make it as a separate project - something like `hs-java-zip` (under correct license) and use that as dependency here.

**Comment by Michael2109** [comment]
No longer required.
