### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by FilipJanitor** [Michael2109/cobalt#400]
We need to keep the codebase tidy so we should decide on some coding standards.  [These](https://github.com/tibbe/haskell-style-guide) seem good as someone pointed out that strictly adhering to 2 spaces sometimes might not be clear with deep nesting. 

The next problem is trailing whitespace and inconsistent file endings as it makes a mess in commits. [See my last commit](https://github.com/Michael2109/cobalt/commit/27cdbe553a1c4182842b145ed43c30dbad3c1870). I think we should use no trailing whitespace and single endline at the end of the file as it is a de-facto standard everywhere and is certainly practical. (To avoid repetitively checking this it will be best to configure the editor to make these adjustments at save)

Currently what I noticed is that in file `Java/ClassPath.hs` there is an issue with formatting the module header  and in `JVM/AssemblerTest.hs`there seems to be indent inconsistency.

I am willing to refactor the code as soon as we settle down on what we actually want - after that when everything will be uniform the work will be easier.

**Comment by FilipJanitor** [comment]
First iteration corrected the style of most of our code. Next we need to focus on java library and tidy the code up (dollars etc).

**Comment by Michael2109** [comment]
After making a lot of changes to datas I've found this format looks better. 
```
data Conditional
    = IfStatement BExpr Expr
    | ElifStatement BExpr Expr
    | ElseStatement Expr
    deriving (Show, Eq)
```
In comparison to what I was originally writing. 
```
data Conditional
    = IfStatement BExpr Expr
    | ElifStatement BExpr Expr
    | ElseStatement Expr
        deriving (Show, Eq)
```

**Comment by FilipJanitor** [comment]
It seems like the guide does not mention this. Whatever seems to make it more clear that the last line is not part of the constructors can be used, so if you prefer the top style we can stick to that.

**Comment by Michael2109** [comment]
After rewriting a lot of things it seems a lot more readable to me so I think we should go for it.

**Comment by Michael2109** [comment]
I think we need to decide what else we would like to focus on for this. We can go and sort out all the parentheses etc but I feel that if it isn't affecting readability by much it probably isn't worth putting the time into. The main things we needed was to get indentation sorted and follow the structure of the document. I feel as long as we continue with this from now onward and correct anything (if there happens to be anything we missed) it should be fine.
