### ISSUE TITLE
Missing documentation: Why does Cobalt offer that Scala doesn't?

### ISSUE THREAD

**Issue by matt2000** [Michael2109/cobalt#42]
The description of Cobolt sounds a lot like Scala. So I would see, why does this project exist? Why would I want to use Cobalt instead of Scala or Clojure? What kinds of projects is it uniquely suited for? Answers to these kinds of questions would help me evaluate if I want to take the time to learn about Cobalt. Thanks for sharing your work!

**Comment by Michael2109** [comment]
Hi Matt!

Currently the overall structure is quite similar to Scala. I'm trying to
head away from this but the designing of the language is in the early
stages so I'm still adding my ideas to the readme.

The two main features I would like to have is automatic synchronisation and
an open type system.

Automatic synchronisation would allow for the user to spend less time
focusing on concurrency issues etc. The Java libraries would still be
accessible so the user would still have access to threads that aren't
synchronised if a higher performance is required.

An open type system would allow for files such as XML and JSON etc to be
read in as though they are objects. If you checkout the readme there's an
XML example.

I feel this language will look at refining down many things from Java,
Scala, or other languages to make things very flexible and also simplistic.
More features will be added throughout the next two weeks and I'm very open
to any suggestions.

Good to hear from you,

Michael

**Comment by Michael2109** [comment]
I've updated the readme.
