### ISSUE TITLE
Remove parenthesis and commas for method arguments

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#428]
To make the code more readable we could possibly remove the parenthesis and commas for method arguments (like haskell). 

**Current**
```
methodCall (x, y)
obj.methodCall(x,y)
```

**Alternative**
```
methodCall x y
obj.methodCall x y 
```

This means we could also use `$` like in Haskell too which can be a lot easier to read. 

I think this could be done. I'm going to try it in a branch and see if this could cause any problems.

**Comment by FilipJanitor** [comment]
Possible downside can be the object oriented way of calling closure functions - I cant explain myself very well, but I am sure that you have already done something like `transform(args)()` where `transform` returns some kind of function that needs to be called. You can call it immediately, but you might not want to. Imagining it doing unambigously without actually using parentheses is not easy for me.  In haskell, this is solved by lazyness.

**Comment by Michael2109** [comment]
I'm going to have to be difficult and ask if you could explain with a basic example? Or is there somewhere I could find more info?

**Comment by FilipJanitor** [comment]
Illustrative python example I threw together in 30 seconds
```
def function():
  return lambda: True
 
a = function()

print(a)
print(a())
```

**Comment by Michael2109** [comment]
One other issue is parsing these. The compiler needs to know that each of these are different.
```
ClassName.methodCall
ClassName.varName
obj.methodCall
methodCall
```

An alternative is we could have a keyword for global val/variables but this isn't tidy. 
```
global.ClassName.methodCall
global.ClassName.varName
```
Although in the first example the compiler should be able to work out if things are class variables etc after parsing is complete.

**Comment by Michael2109** [comment]
I think this is all possible using a similar syntax to F#. It would be more of a matter of considering these to all be identifiers. Then using the symbol table we can decide whether a method is references or a variable etc. 
I'm going to try this later but I feel it is possible. It may be that all method call parsers etc and all parsed using one parser. This won't be easy but if we can get something like this working it would be brilliant.

**Comment by Michael2109** [comment]
After a lot of discussion about this it seems the best approach is to include parenthesis. It means we can parse the code easier and overall the code will be more readable.
