### ISSUE TITLE
Add inline definitions

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#434]
- [x] Methods
```
  method1 (): Int = 100 * exampleVariable
```
- [ ]  If statements
```
    if(True) println ("if")
    elif(False) println ("elif")
    else println ("else")
```
- [x] Multiple inline 
These will be separated with `;`
```
    if(True) println ("if"); print ("Second statement")
    elif(False) println ("elif"); print ("Second statement")
    else println ("else"); print ("Second statement")
```
For parsing multiple inline statements it would probably be best to create a new parser. The inline method definition and if statements can then use this parser.

**Comment by Michael2109** [comment]
This can be done using similar code in the lambda parser and assign parser.

**Comment by Michael2109** [comment]
Which do you prefer?

### 1.

Inline
```
if True then  # Do something
elif True then  # Do something
else  # Do something
```
Block
```
if True then do
    # Do something
elif True then do
    # Do something
else do
    # Do something
```

### 2.

Inline
```
if (True) then  # Do something
elif (True) then  # Do something
else  # Do something
```
Block
```
if (True) then do
    # Do something
elif (True) then do
    # Do something
else do
    # Do something
```

### 3.

Inline
```
if (True) # Do something
elif (True) # Do something
else # Do something
```

Block
```
if (True) do 
    # Do something
elif (True) do
    # Do something
else do
    # Do something
```

I quite like the first one although it could be strange that it doesn't use parenthesis. Seeming as it is enclosed within the `if` and `then` there is no reason we couldn't parse both formats for example 1 and 2.
3 seems a bit strange with placing a `do` after it. I'm not sure if it is as readable overall. 
Also I found a page a while ago (I can't find it now..) about what people preferred in terms of readability for if statements. Overall the if then was the favourite.

**Comment by Michael2109** [comment]
Inline(Can be inserted into other code) The equivalent of using a ternary operator. 
```
let x = if True then 10 else 20
```
```
println ("Inline Example " + (if True then 10 else 20))
```

General if statements

Inline
```
if True then  # Do something
elif True then  # Do something
else  # Do something
```

Block
```
if True then
    # Do something
elif True then
    # Do something
else
    # Do something
```

If we happened to find that the general if statements are inside code then we would throw an error when checking the AST. The first example would be the only one allowed to be inserted into other code. 
I imagine I've missed something so let me know if this won't work for certain cases.

**Comment by FilipJanitor** [comment]
First one is the delcarative - it is an expression. You can imagine it as a mathematical function `if bExpr then expr else expr` is `f(bExpr, expr, expr) = expr` that evaluates the `bExpr` and if it is true returns second argument, if false returns the third. I see no reasonable way to do the general inline version if else is not compulsory without braces. There is a possibility to omit it altogether and leave only the block version, or parse only a single statement after that. But still I think it would cause problems with nesting.

**Comment by Michael2109** [comment]
Why would there be a problem with the else? 
You know anything inline after the else is part of it.

**Comment by FilipJanitor** [comment]
It is the trailing else problem
```
if x>0 then print(x); if x==0 then x++; if x==y then x--;
else y++;
```
where it is not clear which `if` does the `else` belong to along with nesting problems.
`if x>0 then print(x); if x==0 then x++; x++;`
Can be parsed as 
`if x>0 then { print(x); if x==0 then {x++;} x++;}`
or 
`if x>0 then {print(x); if x==0 then {x++; x++;}}`
or maybe possibly
`if x>0 then {print(x); if x==0 then {x++;}} x++;`

**Comment by Michael2109** [comment]
So this is just a matter of removing the general inline example and only parsing the first and last?

**Comment by FilipJanitor** [comment]
Technically yes, that seems like an easy solution

**Comment by FilipJanitor** [comment]
Ok, it seems like I am getting lost in the parsing and can't write my idea with reasonable efficiency. Here is improved pseudocode for general parser (the statement one, not the expression one) that I am confident will work. Currently, there is data `expr` which has constructor `Block [stmt]` and data `stmt` has constructor for if, so nesting should be seamless with only minor changes to AST. We will need to change `If` constructor to `If bExpr Expr (Maybe Expr)`
```
controlParser :: Parser stmt
controlParser = do
    condition <- choice [ try $ parens bExpr, bExpr]
    rword "then"
    stmts <- --indented block of statements
    elsePart <- optional elseParser
    return $ If condition stmts elsePart

ifStatementParser :: Parser stmt
ifStatementParser = do
    rword "if"
    return $ controlParser

-- returns Block[stmt]
elseParser :: Parser stmt
elseParser = do
    choice [elseP, elifP]
  where
    elseP = do
        rword "else"
        return --indented block of statements
    elifP = do
        rword "elif"
        nested <- controlParser
        return Block[nested]
```

**Comment by Michael2109** [comment]
I've been thinking about using `elif` in the inline version. 
In the strange case of doing this we could nest it like you mentioned.

Here's what I proposed.
```
let x = if True then 10 elif True then 20 else 30
```
Here's the nesting you suggested (unless you was thinking of a different way) that produces the same thing.
```
let x = if True then 10 else (if True then 20 else 30)
```

If the main concern is readability I feel the first example is better. It would could be nice that if we can use elif in block statements that we can also use it inline.   
Of course this is just a small example so it might become untidy if done differently.

**Comment by FilipJanitor** [comment]
It could work if we wanted to for sure (with switch-like semantics) but I feel that a code that would need to use such expressions needs refactoring. The inline expression version is basically mimicking the semantics of normal ternary operator, which is a normal function `(_?_:_) = bExpr ✕ expr ✕ expr -> expr` The `if then else `instead of `?:` is just a syntactic sugar with very little common with the statement version so adding elif makes it a bit confusing don't you think?

**Comment by Michael2109** [comment]
Although technically an `if then else` is a ternary in the background there may be the case that the user does want to essentially have a switch. It would mean that in that case they could write it in a neat way in comparison to having to write it using the second method. 
I think overall if we can make the code more readable it would make more sense to allow the first option. I'm thinking if there isn't a technical reason as to why we should avoid this then it could be a nice addition.

**Comment by FilipJanitor** [comment]
The question is, whether such complex expression (I am not sure - the number of `elif`s is unbounded?) is more readable then just separating it to statements
```
if (first expr) then
    res  <- 10
elif (second expr) then
    res <- 20
else
    res <- 30
```

**Comment by Michael2109** [comment]
That is the thing of whether we let the user decide when to use it or restrict them and say they cant. They may want to just do exactly what my example had which would be nicer then them having to create a variable outside or use nested ifs. 
I've come to the conclusion of putting this idea on hold for now. Best to get in the normal features first and if we think this is useful later we can add it as it possibly isn't worth it.

**Comment by Michael2109** [comment]
I've gotten this working with `if elif` or `if else` but not with `if elif else` or `if elif elif`. It is almost there but I had to make a few changes. 
If in the `elifP` part we could successfully run the `elseParser` again and pass it through it would work but the indentation code makes this difficult.

**Comment by Michael2109** [comment]
I'm trying to add a `do block` parser and I'm questioning how this can be done.    
Lets say we want to parse this.
```
let method() = do
    x
    y
    z
```
Currently we have all parsing occur inside an `L.indentBlock`. E.g. in `methodDoBlock`. 
```
methodParser :: Parser Method
methodParser = do
    method <- choice [methodDoBlock, methodInline]
    return method
  where
    methodInline = do
        (annotations, modifiers, name, fields, returnType) <- methodStart
        expression <- expressionParser
        return $ Method name annotations fields modifiers returnType $ ExprAssignment expression
    methodDoBlock = L.indentBlock scn p
      where
        p = do
            (annotations, modifiers, name, fields, returnType) <- try $ do
                start <- methodStart
                rword "do"
                return start
            return (L.IndentSome Nothing (return . (Method name annotations fields modifiers returnType) . StmtAssignment . BlockStmt) statementParser)
    methodStart = do
        (annotations, modifiers) <- try $ do
          anns <- many annotationParser
          mods <- modifiersParser
          rword "let"
          return (anns, mods)
        name <- nameParser
        fields <- parens $ sepBy fieldParser $ symbol ","
        symbol ":"
        returnType <- typeRefParser
        symbol "="
        return (annotations, modifiers, name, fields, returnType)
```
`L.indentBlock` gets the indentation as soon as it starts parsing from that point. It parses `methodStart` and bases indentation on the current position (Which would be `let` in our example). 

Now onto our problem.
We want an individual `do block` parser. 
This is what we would imagine it looking like. 
```
doBlockParser :: Parser Stmt
doBlockParser = L.indentBlock scn p
  where
    p = do
        rword "do"
        return $ L.IndentSome Nothing (return . BlockStmt) statementParser
```
This would be okay but it takes the indentation from the position of the `do` keyword. Not the position of `let`! This would mean to successfully parse the code would have to look like this instead.
```
let method() = do
                   x
                   y
                   z
```

With this in mind I thought we could instead have it that the `do block` parser allowed for you to pass the previous parser (For `let method() =`) in so it could parse it within the indent block.
```
doBlockParser :: Parser Void -> Parser Stmt
doBlockParser preParser = L.indentBlock scn p
  where
    p = do
        previous <- preParser
        rword "do"
        return $ L.IndentSome Nothing (return . BlockStmt) statementParser
```
I thought this would work but what about if the pre parser needs to return information? In this example the pre parser would extract the method name and fields. This means that this parser needs to take a parser that could return an unknown amount of data back.    
We could write it like this but other parsers may return different things.. 
```
doBlockParser :: Parser (String, [Field])-> Parser Stmt
doBlockParser preParser = L.indentBlock scn p
  where
    p = do
        previous <- preParser
        rword "do"
        return $ L.IndentSome Nothing (return . BlockStmt) statementParser
```
Really what we need is it to allow any parser with any return type to be passed in.

**Comment by FilipJanitor** [comment]
That is an interesting observation. I did not know that the indentation is taken from current position instead of start of previous line. The parser wrapper seems like a good idea because we already know that the parser wrapper (`do INDENT ` parser)only returns `BlockStmt`, so it should be possible to plug it in the next constructor.  I dont understand the indenting magic but would it not be possible to sort of reverse the operation - instead of wrapping some parser in `do INDENT` parser, we would plug the `do INDENT` parser into the `method` or `assignments` or any other parser and when calling it inside, we would somehow send it the correct position from which the do parser should indent? Because after further thinking and trying to understand how are the blocks parsed currently I am starting to feel that actually the new `data` I proposed in the PR, that would distinguish between expression and statement is redundant and unnecessary and we can do it this way. Still, what we are trying to do now is to sort of abstract the indenting away in order to not repeat code in the parsers.

**Comment by Michael2109** [comment]
I've just found out megaparsec has `indentLevel` so maybe we can have it that the do block parser takes the current indentation value and parses depending on that. That could be a solution. Not sure how the body of the parser would look but the fields could be like this. 
```
doBlockParser :: Int -> Parser Stmt
doBlockParser indentation = L.indentBlock scn p
  where
    p = do
        rword "do"
        return $ L.IndentSome Nothing (return . BlockStmt) statementParser
```
If we can get this working we can remove a lot of repeated code. It means we can just use `choice [doBlockParser, expressionParser]` in theory which would be a lot nicer.

**Comment by FilipJanitor** [comment]
That would be great. Since we are wrapping it to the `BlockStmt`, it is now clear, that my idea was wrong and this will be much more elegant.

**Comment by Michael2109** [comment]
Why can the datas for distinguishing expression and statement be removed if we do it this way?

**Comment by FilipJanitor** [comment]
Because I did not know we can force the `Stmt` in `Assign Name (Maybe Type) Stmt`  be `BlockStmt[Stmt]` by wrapping the parsed things into that constructor using `do INDENT` parser wrapper (when choosing in `choice [doBlockParser, expressionParser]`), and the result of expressionParser in `ExprAsStmt` constructor. But this might be a premature optimisation, if you feel that the new data would make things easier, I will not protest.

**Comment by Michael2109** [comment]
Yeah I don't think we will need them. Although it does depend on if we think it could be easier to know if something is only an expression or a block. Not sure if there are any cases for that though.

**Comment by Michael2109** [comment]
I can't get it working when parsing an indented block when specifying the current indentation. According to the datas I would have thought I'm doing it right. 
```
data IndentOpt m a b
  = IndentNone a
    -- ^ Parse no indented tokens, just return the value
  | IndentMany (Maybe Pos) ([b] -> m a) (m b)
    -- ^ Parse many indented tokens (possibly zero), use given indentation
    -- level (if 'Nothing', use level of the first indented token); the
    -- second argument tells how to get final result, and third argument
    -- describes how to parse an indented token
  | IndentSome (Maybe Pos) ([b] -> m a) (m b)
    -- ^ Just like 'IndentMany', but requires at least one indented token to
    -- be present
```

Do Block Parser
```
doBlockParser :: Pos -> Parser Stmt
doBlockParser indentation = L.indentBlock scn p
  where
    p = do
        rword "do"
        return $ L.IndentSome (Just indentation) (return . BlockStmt) statementParser
```

Method Parser
```
methodParser :: Parser Method
methodParser = do
    method <- choice [methodDoBlock, methodInline]
    return method
  where
    methodInline = do
        (annotations, modifiers, name, fields, returnType) <- methodStart
        expression <- expressionParser
        return $ Method name annotations fields modifiers returnType $ ExprAssignment expression
    methodDoBlock = try $ do
        indentation <- L.indentLevel
        (annotations, modifiers, name, fields, returnType) <- methodStart
        doBlock <- doBlockParser indentation
        return $ Method name annotations fields modifiers returnType $ StmtAssignment doBlock
    methodStart = do
        (annotations, modifiers) <- try $ do
          anns <- many annotationParser
          mods <- modifiersParser
          rword "let"
          return (anns, mods)
        name <- nameParser
        fields <- parens $ sepBy fieldParser $ symbol ","
        symbol ":"
        returnType <- typeRefParser
        symbol "="
        return (annotations, modifiers, name, fields, returnType)
```

The `methodDoBlock` gets the indentation correctly as I've output the value it is getting to check. There is no difference in putting `Nothing` or `Just indentation` in the `doBlockParser`. 
The error that is occurring is that it is considering the initial indentation to be at the `do` keyword. 
This would parse for these examples.
```
let method() = do
                   x
                   y
                   z
```
Instead of this.
```
let method() = do
    x
    y
    z
```

**Comment by Michael2109** [comment]
I realise now I have misread the datas. It's not the level of the non indented token like I'm currently using. It's the expected level of the indented token. If this is true then I need to take a different approach. 

```
-- level (if 'Nothing', use level of the first indented token); 
```
