### ISSUE TITLE
Remove `let` from value definitions

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#435]
```
# Value
exampleValue: Double = 10.54

# Variable
mutable exampleVariable: Int = 10
```

- [ ] Parser
- [ ] Tests
- [ ] Update documentation

**Comment by FilipJanitor** [comment]
Just to clarify - we will use different operator for reassignment, right?

**Comment by Michael2109** [comment]
Yeah I missed this out when adding the issues. I'll add it now.

**Comment by Michael2109** [comment]
This is no longer required as we are using the `let` keyword.
