### ISSUE TITLE
Nested methods

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#436]
We need to parse nested methods. 
```
# Nested method
getEven (list: List[Int]): List[Int]
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

- [ ] Parser
- [ ] Tests
- [ ] Update documentation

**Comment by FilipJanitor** [comment]
How would it look like if we wanted to send the result of isEven to filter? (It is of course nonsense, but just to give an example)

**Comment by Michael2109** [comment]
```
# Nested method
getEven (list: List[Int]): List[Int]
  isEven (num: Int) = num % 2 == 0
  valStoringIsEven = isEven
  valOfIsEven = isEven(10)

  parameterlessMethod() = 1000
  storingParameterlessMethodInVal = parameterlessMethod
  callingAndStoringValue = parameterlessMethod() 

  list.filter(isEven)
```

Another example with a lambda that would do the same as the original example. 
```
# Nested method
getEven (list: List[Int]): List[Int]
  isEven (num: Int) = num % 2 == 0
  list.filter(x => isEven(x))
```

**Comment by Michael2109** [comment]
With this we need a way of differentiating between a method definition and a method call. If we ever were to introduce type inference in the future we would get problems. 

This would work fine:
```
getEven (list: List[Int]): List[Int]
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

But this wouldn't when having no fields present and no return type:
```
getEven ()
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

We could work out whether it is a method call by looking to see if there is code contained within it like in the example. This could work but we may want empty definitions and we want the user to easily tell the difference between methods and method calls.    

I'm thinking of a Haskelly `do` version. I quite like this and can't see any problems with it. 
```
getEven () = do
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

We could also have it without `do` although that would make it more difficult to tell between inline and block code. Also it seems a bit strange having no code after an equals, 

```
getEven () = 
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

**Comment by FilipJanitor** [comment]
Explicit `void` could help in definitions

**Comment by Michael2109** [comment]
Do you mean like this? 

```
getEven (): void = 
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

**Comment by FilipJanitor** [comment]
I am not entirely sure about the syntax but that could work, or even `parameterlessFunction(:void) = ` could be more concise

**Comment by Michael2109** [comment]
Although adding void could work we may want type inference which would mean we don't want to specify a type. Makes it a bit more difficult. 

I think we may want to introduce something like `Unit` in Scala. Scala uses this instead of void for if you don't want to return anything. 

The tidiest way of doing this (in my opinion) is this. I think adding `:void` inside the parameters might be a bit more difficult to read. 

```
getEven () = do
  isEven (num: Int) = num % 2 == 0
  list.filter(isEven)
```

Although if you have any other ideas feel free to add. :)

**Comment by FilipJanitor** [comment]
It still is quite ambiguous this way. You have a name followed by parentheses so the reader first parses it as function call. After that there is an equals sign, which seems like some kind of assignment, but on the lefthand side there is an expression which does not make sense again. It is after all this when the reader finally notices the `do` and realizes that we are actually defining a function.

Possible suggestion is to further alter the language with some function prefix. For example Python has it done nicely. There is `lambda` for lambdas and `def` for functions in any scope. In addition to this, syntax highlighting can highlight the `def` keyword so even without careful examination it is clear how is the code structured.

**Comment by Michael2109** [comment]
With that in mind it could be better to have a prefix. Also have the option of `let` too,    

Will have to have a think about it and make some examples to see. I quite like the idea of having it completely minimal where possible but it may be better to add a prefix.

**Comment by Michael2109** [comment]
Taking what you mentioned into consideration. Here is an example without using a prefix and with a prefix.  
```
class exampleClass

    exampleMethod1() = do
        x = 10
        exampleNestedMethod() = do
            println ("Do something")
        exampleNestedMethod()
        exampleMethod()
```
I agree with you. Looking at this together with method calls is confusing. 

```
class exampleClass

    let exampleMethod1() = do
        let x = 10
        let exampleNestedMethod() = do
            println ("Do something")
        exampleNestedMethod()
        exampleMethod()
```
I like the idea of using `let`. I prefer it to `def` more  as I've always considered `def` to be defining methods and not methods and values.

**Comment by FilipJanitor** [comment]
Yeah, the second example is definitely clearer. Regarding the use of `let` for both methods and values, how about the plan to include some kind of block members of classes? Setters and getters if I recall correctly. Would not these blocks make it ambiguous again? Or is it an intended behavior? Sorry if it is completely unrelated.

**Comment by Michael2109** [comment]
What do you mean by block members for classes? Do you have an example?

**Comment by Michael2109** [comment]
```
# Variable
let x = do
    // Do something
    if (notX < 50)
        1000
    else 
        -343

# Method
let z () = do 
    // Do something
    ...
```

**Comment by Michael2109** [comment]
I've added the `let` reserved word for method definitions. Nested methods can now be used.
