### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#437]
We need to parse pattern match statements.
```
  # Case
  exampleCase (obj: Object) =
    # Pattern matching must be exhaustive
    match obj with
      ClassName1 -> println ("Is type ClassName1")
      ClassName2 -> println ("Is type ClassName2")
      (_)        -> println ("Default option")
```
```
match obj with
    1 -> println ("Is type ClassName1")
    2 -> println ("Is type ClassName2")
    (_) -> println ("Default option")
```

Multi line
```
  # Case
  exampleCase (obj: Object) =
    # Pattern matching must be exhaustive
    match obj with
      ClassName1 -> do
          println ("Is type ClassName1")
          println ("Second statement")
          println ("Third statement")
      ClassName2 -> println ("Is type ClassName2")
      (_)        -> println ("Default option")
```

A separate parser should possibly be created for the cases such as this.
```
ClassName1 -> println ("Is type ClassName1")
```

This will allow for the code to look similar to this with the indentation parsing. 
```
return (L.IndentSome Nothing return caseParser)
```

The case parser would have to deal with `inline` and `do block` parsing. This should be very similar to the `methodParser`. 

- [ ] Parser
- [ ] Tests
- [ ] Update documentation

**Comment by mlutze** [comment]
I got a small start on this issue in commit 8d052e7f18bee439719dc55fd4fdca8ace98e7eb, but I wanted to get a thumbs-up on the direction I'm headed before I continue. In particular, the way I have implemented the AST currently has `Case` at top-level, which doesn't seem quite right to me. I think with a proper AST for this feature to guide me, the implementation would be quite a bit easier.

**Comment by Michael2109** [comment]
Just at a glance. I think the case should store an `Expr`  instead of `Name`. Expressions such as `True`, `100` or `varName` might be used. 
In terms of the code after the `->` we would want to store this in the `Assignment` data type. This is used for us to either store an expression (inline) or statement (multiline). The method parser and lambda parser should help you a lot with this.  
This is what I think it should be.
```
Case Expr Assignment
```
I added a comment for one part to change to adjust for this data structure.
