### ISSUE TITLE
Lambdas

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#440]
Add parsing of lambdas

```
# Lambdas (Shorthand for anonymous functions)
exampleLambda(x: Int): Int => x + 1
```

Python
```
lambda x: x + n
```

F#
```
fun x y -> x + y 
```

Java
```
x y -> x + y
```

Scala
```
x y => x + y
```
Lambdas should be able to be passed as arguments to methods/classes. (Add the lambda parser to the argument parser).

- [ ] Parser
- [ ] Tests
- [ ] Update documentation

**Comment by Michael2109** [comment]
Personally my favourite is the Java version. It's clean and doesn't use any symbols we are currently using. 
The problem in terms of readability with `=>` and `:` is that the first contains an `=` operator. The latter is the syntax we are using for defining types (E.g. x: Int) so it might be nicer having a separate symbol. 
I like the idea of using `lamba` or `fun`  in front of the definition but removing it for a more simplistic approach might be nicer.

**Comment by FilipJanitor** [comment]
how about haskellish `\` before lambda?  The Java or Scala styles are not bad but for me personally it does not really stand out in the code. This is amplified if the `<-` is going to be used for assignment.

**Comment by Michael2109** [comment]
That is a good point. This means we could use `lambda`, `func`, or `\`.

**Comment by Michael2109** [comment]
Okay so I think it's best to write a couple examples including reassignment, method definitions and the lambda syntax we would like.

Using `->`
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(value -> value * 2)
```

Using `\x ->`
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(\value -> value * 2)
```

Using `=>`
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(value => value * 2)
```

Using `lambda x ->`
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(lambda value -> value * 2)
```

Using `fun x ->`
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(fun value -> value * 2)
```
I quite like the `fun` one. Also having a prefix will mean we can give more specific parsing errors.

**Comment by Michael2109** [comment]
Lambdas containing blocks of code. 

This gives good reason for us to use do as it makes it much easier for us to know when a block of code is expected. 
```
let exampleMethod() = do
    let mutable x = 1000
    x <- 100
    let list: List[Int] = List(1,2,3)
    list.map(fun value -> do
        # Do something
        value * 2
    )
```

**Comment by Michael2109** [comment]
Forgetting we need to include types and multiple variables. 

```
fun (i: Int) -> i
```
```
fun i j -> i
```
