### ISSUE TITLE
Reassigning variables

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#442]
The `<-` operator will be added. This will allow us to distinguish between creating a new variable/value and reassigning a new value to a variable.

```
# Reassigning a variable
exampleVariable <- 20
```

**Comment by FilipJanitor** [comment]
we can even use pascal like operator `:=`

**Comment by Michael2109** [comment]
I decided to go for the `<-` symbol. It's clean and quite different from the `=` operator so it stands out.
