### ISSUE TITLE
Add tuples

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#446]
```
let x, y = 10, 20
```
```
let _, y = 10, 20
```

**Comment by Michael2109** [comment]
What happens in this case? 
```
methodCall(1, 2, 3, 4, 5)
```
I'm assuming when used as arguments you have to wrap it in parenthesis? 
```
methodCall(1, 2, (3, 4), 5)
```

**Comment by FilipJanitor** [comment]
You are right, this is a Go disadvantage, to quote:

> There is no tuple type in Go, the multiple values returned by functions do not represent a first-class object.

**Comment by Michael2109** [comment]
I wonder if it might be better to always enclose it in parenthesis to keep it the same throughout.

**Comment by FilipJanitor** [comment]
If we insist on having the real tuple (not just the ability to return multiple values from a function) then yes, it seems like the only logical approach. 

Just another food for thought - how to write single tuple? Python uses `(1,)` for tuple containing single value - in this case `1`

**Comment by Michael2109** [comment]
Are there any use cases for that? I'm trying to think of why you wouldn't just return an `Int` instead?

**Comment by FilipJanitor** [comment]
Despite having a dim memory that I have used it somewhere at some time I cant think of anything practical at the moment. It makes everything concise however - you can have tuple with any natural number of elements (including zero) so why make 1 an exception?

**Comment by FilipJanitor** [comment]
Yeah, after some thinking it looks like that in Python it is used because of list mutability - there are functions that return variable length tuples. Since our basic structures are going to be immutable, it really can be replaced by list in such cases and the slight inconsistency does not matter.

**Comment by Michael2109** [comment]
Ah that makes sense. 
When you say it can be replaced by list do you mean completely?

**Comment by FilipJanitor** [comment]
In the case of function returning tuple of variable length. That is the only real world scenario I was able to find (but there must be something else, I remember writing it somewhere) so I assumed that in that case a list would be sufficient.

Nope, tuples seem to be used in `*args` which is used for variable number of nonpositional arguments. 
Inside this function
```
def fun(*args):
    body
```
the `args` is a tuple containing arguments provided. In case of using only one argument, it is a single value tuple

**Comment by Michael2109** [comment]
Yeah I think we would probably want to stick to immutable then. We would want it for returning various types as a list would have to be a list of objects. It would be a nice extra feature.

**Comment by Michael2109** [comment]
I've added parsing for tuples using parenthesis as this makes the most sense. For multiple variable assignment I'll raise a separate issue.
