### ISSUE TITLE
data Conditional is redundant

### ISSUE THREAD

**Issue by FilipJanitor** [Michael2109/cobalt#450]
For data `Stmt` we have a constructor `If conditional (Maybe conditional)` which is redundant. It is implicit that the first part must be `if` and second must be `else`, since we are desugaring `elif` to simple nesting. Instead I suggest replacing it with constructor  `If BExpr Expr Expr` in `Stmt` where the `Expr`should be `Block [Stmt]` (as we discussed earlier, this might be moved from `Expr` data somewhere else, possibly to `Stmt` too)

There should be separate constructor in `Expr` for the inline ternary replacement. If we decide to limit it to no or one `elif`, we can devise similar constructor for data `Expr` thus completely eliminating `Conditional`. If we decide for the switch like expression with unbounded number of `elif` this can still be implemented using `List` in constructor in data `Expr`, so the `Conditional` seems redundant.

**Comment by FilipJanitor** [comment]
After further thinking it seems to me that using `List` is unnecessary. We can desugar and nest the expressions in the exact same way as we would do with statements

**Comment by Michael2109** [comment]
Yeah this can all be done in the same way as the normal if but instead only allow an expression in the body of the if and else. 
With this we need to organise the Expr and Stmt constructors. Certain ones are containing things they shouldn't such as `Block[Stmt]` isn't an expression.

**Comment by FilipJanitor** [comment]
Exactly, and since the inline `if` is and expression too, this approach will allow both expression nesting and using the elif sugar
