### ISSUE TITLE
Separate expressions and statements out correctly

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#451]
Currently expressions and statements are a bit muddled. E.g. `Block [Stmt]` is an expression but instead should be a statement.    
All of these need to be organised correctly. 
Also ExprParser shouldn't be called ExprParser if it deals with statements too.

**Comment by FilipJanitor** [comment]
This is probably caused by several facts, for example:
We allow block assignments/setters (sorry - I always forget the name of this feature). From the premise, that in assignment we are assigning a value of expression to variable, the `Block [Stmt]`makes sense.
Also, function call can be either a statement (if its return value is not stored) or an expression (it can even be a part of bigger expression, some relation or something)

**Comment by Michael2109** [comment]
Although with assignment for us it either could be an expression or statements. Really assignment should just parse statements which would mean it should be the other way around. This all gets a bit muddled as variables can be initialised using a block of code.

**Comment by FilipJanitor** [comment]
Yeah, the block assignment is an exception to the simple informal rule - statements do something and expressions evaluate to something.

**Comment by Michael2109** [comment]
This is going to make things confusing though as there will be strange cases. I'll try swapping everything around first and we can make the small changes after. 
I've got it building fine in branch `cobalt-434-451`. It still needs a lot of changes and all of the tests to be fixed though.

**Comment by Michael2109** [comment]
I've been thinking and I'm not sure if we need the `Block [Stmt]` one. We could keep it but we may as well just use `[Stmt]` instead as I'm not sure if there is any need for the wrapper. 
In what I'm working on I've moved `Block [Stmt]` to the `Stmt` data and changed it to `Block [Expr]`. There is a problem here though of if a parser (E.g. an expression block parser) parses a block of expressions, there may also be statements contained in it. So this method doesn't work.     
Really for method bodies and others we want to consider an expression to be a statement in a way. It might be useful having something like `Expression Expr` inside the `Stmt` data. Or the other way around where `Expr` contains a list of `Stmt` but it doesn't make sense to do that. 
The main problem is that in some situations we want to parse expressions and statements as though they are the same thing. Of course they are not though. 
As an example. How do we parse a combination of expressions and statements? 
We currently have a method parser that returns `[Stmt]`.
```
exampleMethod() = do
    x    # Expr
    y    # Expr
    z    # Expr
    if (True)    # Stmt
        if (False)    # Stmt
            println ("Do something")    # Stmt
        else
            println ("Do something")    # Stmt
    else 
        println("Do something")    # Stmt
```

**Comment by FilipJanitor** [comment]
I think the Block wrapper is a good visual cue for us that helps with
maintaining scopes. In your example, I think the first three lines
containing x,y,z can be safely assumed to be statements as their result is
not used anywhere. Just like with C simple assignment or `x++` could be an
expression or statement depending on context.

**Comment by Michael2109** [comment]
The problem with this is how we deal with this when parsing. We have individual parsers for expressions and statements and this would mean that we probably need another parser that parses expressions (E.g. identifiers) and wraps them inside a statement. This would allow for the method parser to just parse an list of statements using the `statementParser` and the `statementParser` would use some sort of "expression to statement" parser.
