### ISSUE TITLE
Parse block of code for assignments

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#471]
When assigning variables we should be able to define them inline or as a block of code. This should be similar code to the method parser. 
```
let x = 10
let y = do
    if True 
    then
        # Do something here
        println ("Do something") 
        20
    else
       # Do something here
        println ("Do something else")  
        50
```

- [ ] Parser
- [ ] Tests
- [ ] Documentation

**Comment by FilipJanitor** [comment]
This seems like using the ternary operator expression inside a statement block. I am not sure what is the benefit if it could be written as 
`let y = if True then 20 else 50` 
or in classical syntax
`let y = True ? 20 : 50`

**Comment by Michael2109** [comment]
I've updated the example. The example is supposed to be for if you have statements instead of an expression. The user may want the variable to be defined by calling a block of code and calculating the answer instead of it being a one line expression.

**Comment by FilipJanitor** [comment]
Ok, that example makes it more clear, but still there is the question as to what actually is a result of a block of statements, if there is no return. From the example I assume, that it might be last evaluated expression/statement if it is possible. This seems to leave a lot to guesswork. What if there is nothing evaluatable in the do block?. For example
```
let y = do
    while (False):
        #anything
``` 

Edit: I have just read what you commented to the other issue so this answer is a bit outdated, still some parts of it make sense I think, so I leave it as it was.

**Comment by Michael2109** [comment]
This can be determined depending on what is within the while loop. We should be able to work out if the same type is always the last to be pushed onto the stack. 
With your example we have two options if the return type is unknown. Either instantly throw an error and require the user set the return type to void/Unit or automatically set the return type to void/Unit in the background (although this could make things confusing).

Specify it is a void type if the return type could vary. (If it was a method)
``` 
let y(): Unit = do
    while (False):
        #anything
```

**Comment by FilipJanitor** [comment]
Hmmm, I still cant wrap my mind around it - is this checkable at compile time (as we are trying to be nonnullable)?

**Comment by Michael2109** [comment]
Sorry my example was wrong. We can't have a void type value.. Can be for a method though. 
Yes this is all able to be done at compile time.

**Comment by Michael2109** [comment]
This is already implemented.
