### ISSUE TITLE
Add a keyword to specify methods only use their arguments

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#499]
I found a discussion about having a keyword to specify if methods only use variables within the methods scope. This seems like quite an interesting way of getting the language a bit more functional. 
```
Modern programming languages need to support referentially transparent functions.

You don't have to go full Haskell. But there should be a way to specify that a function shall only operate on its inputs (if any) and shall have absolutely no side effects. This allows you to separate code that mutates state (or has other side effects) and code that doesn't.
```

**Comment by mlutze** [comment]
I think `pure` would be a good choice of keyword for this. Alternately, if we *really* want to encourage functionality, we could require an `impure` keyword on methods with side-effects.

**Comment by Michael2109** [comment]
I like `pure`. It describes exactly what it is. 
We could use `impure` but I imagine with it being an object-oriented language people are more likely to use `impure` most of the time. This might make it a bit more difficult to read. 
Could pure also be a modifier for classes and objects? Like `final` it would mean all methods inside it are pure.

**Comment by FilipJanitor** [comment]
Would the semantics be like `const` member functions in c++ where they are not allowed to modify the object they are being called on or would it be like totally pure functions in terms of having no sideeffect and not mutating anything at all?

**Comment by Michael2109** [comment]
I would think no side effects at all. The fields would be final automatically (or throw an error if not set as final) and the method body can't access anything outside its scope. This also means no allowing of reassignment.
