### ISSUE TITLE
Numbers - Code generation

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#503]
We need to generate byte code for numbers. Depending on which type of number means different operators are used to push onto the stack. 
This includes printing out the numbers. 
A check should be made during the IR  stage to ensure that the values are within the min/max bounds. 
Tests should be added to ensure it works with the min/max values. 

- [x] Integer
- [x] Long
- [x] Float
- [x] Double

**Comment by Michael2109** [comment]
I'm having some trouble with this. Do you know how to correctly extract a float/integer from a `Scientific` data type? That's all I need to do to generate code. 
I've currently commented out the code in `CodeGen` that requires this.

**Comment by FilipJanitor** [comment]
Have you tried this http://hackage.haskell.org/package/scientific-0.3.5.2/docs/Data-Scientific.html#v:floatingOrInteger

**Comment by Michael2109** [comment]
Yes although I've been getting errors using it. I'll continue looking at it as it must be something I'm missing.

**Comment by Michael2109** [comment]
I'm going to copy my current code here for reference as I'm tidying up the `CodeGen` module. 
```
genLongConst value
    | value == 0 = lconst_0
    | value == 1 = lconst_1
    | value >= -128 && value <= 127 = bipush $ fromIntegral value
    | value >= -32768 && value <= 32767 = sipush $ fromIntegral value
    | otherwise = error $ show otherwise

genDoubleConst value
    | value == 0 = lconst_0
    | value == 1 = lconst_1
    | value >= -128 && value <= 127 = bipush $ fromIntegral value
    | value >= -32768 && value <= 32767 = sipush $ fromIntegral value
    | otherwise = error $ show otherwise

genCode (IR.LongConstIR value) = do
        let intValue = case toBoundedInteger value of
                           Just (Int i)  -> i
                           Nothing -> error "Long value cannot be floating point precision"
        genLongConst intValue

genCode (IR.DoubleConstIR value) = do
        let doubleValue = toRealFloat value
        genDoubleConst doubleValue

```
