### ISSUE TITLE
Double parsed without a `.`

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#504]
Expression parser
```
    <|> LongConst <$> longParser
    <|> FloatConst <$> floatParser
    <|> DoubleConst <$> doubleParser
    <|> IntConst <$> integerParser
```
If a value of `10` is input then it is parsed successfully with the double parser. Instead the double parser should only parse correctly if a `.` is in between.

**Comment by FilipJanitor** [comment]
I could not reproduce this. When parsing a couple of normal numbers using `expressionParser` the result is wrapped in `IntConst` which is the expected behavior. Do you have some special input where it fails?

**Comment by Michael2109** [comment]
Did you add the 'doubleParser back into the expression parser? I temporarily removed it. 
It should be that if all 4 number parsers are in the expression parser like my example it would parse '10' as a double.

**Comment by FilipJanitor** [comment]
Ah, sorry I missed it - I was only scanning for comments and did not realize the line is removed completely. Yeah, it seems to not work if `DoubleParser` is before `IntegerParser` Maybe this can be solved in the typechecking stage or we can explicitly enforce the dot inside double parser as it seems like the `L.scientific` parses even normal integers.

**Comment by Michael2109** [comment]
I'm wondering if it should instead be parsed using `L.float`? I think that might only parse if a dot is in between. Although I doubt that will work as we need the higher precision.

**Comment by FilipJanitor** [comment]
what is the state of this now please? It seems to be working OK - that means `10` is parsed as `IntConst` and `10.0` as `DoubleConst`

**Comment by Michael2109** [comment]
I think this is probably fixed as I changed to use `L.float`. If you're happy with it we can close it.
