### ISSUE TITLE
Add casting variables

### ISSUE THREAD

**Issue by Michael2109** [Michael2109/cobalt#515]
We need to add casting between variables. 

Java
```
(ClassName) new ChildName()
```
Scala 
```
new ChildName().asInstanceOf(ClassName)
```

**Comment by mlutze** [comment]
I'm partial to Scala's method. It feels like an appropriate functional/object oriented mix, rather than the added syntax in Java.

**Comment by Michael2109** [comment]
Yeah I've always struggled with the Java one. It doesn't feel natural to write a cast before the variable as normally you type out the variable first then realise you need to cast it next. The Scala format means you do everything from left to right. 
I'll leave this open for if we have any new ideas. Otherwise if we use the Scala format it requires no changes for now.

**Comment by Michael2109** [comment]
Not required as it will be parsed as a method call.
